-- PostgreSQL schema for jcloud (compatible with Neon)
-- Canonical schema for the current PostgreSQL setup

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS files (
    file_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    owner_id INTEGER,
    upload_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_files_owner FOREIGN KEY (owner_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS chunks (
    chunk_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id INTEGER,
    chunk_index INTEGER,
    chunk_size INTEGER,
    CONSTRAINT fk_chunks_file FOREIGN KEY (file_id) REFERENCES files(file_id)
);

CREATE TABLE IF NOT EXISTS nodes (
    node_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_name VARCHAR(50),
    ip_address VARCHAR(50),
    port INTEGER,
    status VARCHAR(20),
    storage_capacity BIGINT
);

CREATE TABLE IF NOT EXISTS chunk_locations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_id INTEGER,
    node_id INTEGER,
    CONSTRAINT fk_chunk_locations_chunk FOREIGN KEY (chunk_id) REFERENCES chunks(chunk_id),
    CONSTRAINT fk_chunk_locations_node FOREIGN KEY (node_id) REFERENCES nodes(node_id)
);

-- Optional performance indexes (not required for schema parity)
CREATE INDEX IF NOT EXISTS idx_files_owner_id ON files(owner_id);
CREATE INDEX IF NOT EXISTS idx_chunks_file_id ON chunks(file_id);
CREATE INDEX IF NOT EXISTS idx_chunk_locations_chunk_id ON chunk_locations(chunk_id);
CREATE INDEX IF NOT EXISTS idx_chunk_locations_node_id ON chunk_locations(node_id);
